import { StyleSheet } from 'react-native';
import Colors from '@styles/colors';
import { editorialShadow } from '@styles/theme';

export default StyleSheet.create({
    container: { flex: 1, backgroundColor: Colors.surface },
    scrollContent: { paddingHorizontal: 16, paddingVertical: 18 },
    card: {
        width: 310,
        backgroundColor: Colors.surfaceContainerLowest,
        borderRadius: 24,
        overflow: 'hidden',
        marginRight: 14,
        ...editorialShadow,
    },
    image: { width: '100%', height: 190, borderTopLeftRadius: 24, borderTopRightRadius: 24 },
    imagePlaceholder: { backgroundColor: Colors.surfaceContainerLow, justifyContent: 'center', alignItems: 'center' },
    cardBody: { padding: 20 },
    name: { fontSize: 22, fontWeight: '800', color: Colors.text, lineHeight: 28 },
    metricGroup: { flexDirection: 'row', alignItems: 'center', marginTop: 14 },
    metricIconWrap: {
        width: 36,
        height: 36,
        borderRadius: 12,
        backgroundColor: Colors.surfaceContainerLow,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    metricLabel: { fontSize: 11, color: Colors.textSecondary, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.7 },
    metricValue: { fontSize: 16, color: Colors.text, fontWeight: '700', marginTop: 2 },
    ingredientPills: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 4 },
    ingredientChip: { marginRight: 6, marginBottom: 4 },
    ingredientChipText: { fontSize: 12 },
    btnRow: { flexDirection: 'row', marginTop: 20 },
    cartBtn: { flex: 1, marginRight: 8 },
    actionBtn: { marginTop: 18, borderRadius: 20 },
    centerState: {
        flex: 1,
        backgroundColor: Colors.surface,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 32,
    },
    errorIcon: {
        width: 72,
        height: 72,
        borderRadius: 36,
        backgroundColor: Colors.primaryLight,
        justifyContent: 'center',
        alignItems: 'center',
    },
    stateTitle: { fontSize: 22, fontWeight: '800', color: Colors.text, marginTop: 18 },
    stateText: { fontSize: 15, color: Colors.textSecondary, marginTop: 10, textAlign: 'center', lineHeight: 22 },
});
