import { StyleSheet } from 'react-native';
import Colors from '@styles/colors';
import { editorialShadow } from '@styles/theme';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.surface,
    },
    content: {
        padding: 20,
    },
    loading: {
        flex: 1,
        backgroundColor: Colors.surface,
    },
    hero: {
        backgroundColor: Colors.surfaceContainerLowest,
        borderRadius: 24,
        padding: 20,
        marginBottom: 16,
        ...editorialShadow,
    },
    title: {
        fontSize: 26,
        fontWeight: '800',
        color: Colors.text,
    },
    subtitle: {
        marginTop: 8,
        fontSize: 14,
        lineHeight: 22,
        color: Colors.textSecondary,
    },
    errorBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.surfaceContainerLow,
        borderRadius: 16,
        padding: 12,
        marginTop: 14,
    },
    errorText: {
        flex: 1,
        marginHorizontal: 10,
        fontSize: 13,
        color: Colors.text,
    },
    card: {
        backgroundColor: Colors.surfaceContainerLowest,
        borderRadius: 24,
        borderBottomLeftRadius: 4,
        padding: 16,
        marginBottom: 16,
        marginLeft: 8,
        marginRight: 8,
        ...editorialShadow,
    },
    cardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    dishName: {
        fontSize: 16,
        fontWeight: '800',
        color: Colors.text,
    },
    customerName: {
        marginTop: 4,
        fontSize: 13,
        color: Colors.textSecondary,
    },
    ratingBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.surfaceContainerLow,
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 9999,
    },
    ratingText: {
        marginLeft: 4,
        fontSize: 13,
        fontWeight: '800',
        color: Colors.text,
    },
    comment: {
        marginTop: 10,
        fontSize: 14,
        lineHeight: 20,
        color: Colors.text,
    },
    commentEmpty: {
        marginTop: 10,
        fontSize: 13,
        color: Colors.textSecondary,
        fontStyle: 'italic',
    },
    date: {
        marginTop: 10,
        fontSize: 12,
        color: Colors.textSecondary,
    },
    filterWrap: {
        marginBottom: 16,
    },
    filterRowHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
        paddingHorizontal: 4,
    },
    filterLabel: {
        fontSize: 11,
        fontWeight: '800',
        color: Colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 0.8,
    },
    clearLink: {
        fontSize: 12,
        fontWeight: '700',
        color: Colors.primary,
        textDecorationLine: 'underline',
    },
    chipRow: {
        gap: 8,
        paddingVertical: 4,
    },
    chip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 9999,
        backgroundColor: Colors.surfaceContainerLowest,
        borderWidth: 1,
        borderColor: Colors.outlineVariant + '50',
    },
    chipActive: {
        backgroundColor: Colors.primary,
        borderColor: Colors.primary,
    },
    chipText: {
        fontSize: 13,
        fontWeight: '700',
        color: Colors.text,
    },
    chipTextActive: {
        color: Colors.onPrimary,
    },
    dishPicker: {
        marginTop: 10,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingHorizontal: 14,
        paddingVertical: 12,
        borderRadius: 14,
        backgroundColor: Colors.surfaceContainerLowest,
        borderWidth: 1,
        borderColor: Colors.outlineVariant + '50',
    },
    dishPickerActive: {
        borderColor: Colors.primary,
        backgroundColor: Colors.primaryLight,
    },
    dishPickerText: {
        flex: 1,
        fontSize: 14,
        fontWeight: '700',
        color: Colors.textSecondary,
    },
    dishPickerTextActive: {
        color: Colors.primary,
    },
    modal: {
        backgroundColor: Colors.card,
        marginHorizontal: 24,
        borderRadius: 24,
        padding: 20,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '800',
        color: Colors.text,
        marginBottom: 14,
    },
    dishOption: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 12,
        paddingHorizontal: 12,
        borderRadius: 12,
    },
    dishOptionActive: {
        backgroundColor: Colors.primaryLight,
    },
    dishOptionText: {
        fontSize: 14,
        fontWeight: '700',
        color: Colors.text,
        flex: 1,
        paddingRight: 12,
    },
    dishOptionTextActive: {
        color: Colors.primary,
    },
    dishOptionEmpty: {
        fontSize: 13,
        color: Colors.textSecondary,
        fontStyle: 'italic',
        textAlign: 'center',
        paddingVertical: 16,
    },
    empty: {
        alignItems: 'center',
        backgroundColor: Colors.surfaceContainerLowest,
        borderRadius: 24,
        paddingHorizontal: 24,
        paddingVertical: 32,
        ...editorialShadow,
    },
    emptyTitle: {
        marginTop: 14,
        fontSize: 18,
        fontWeight: '800',
        color: Colors.text,
        textAlign: 'center',
    },
    emptyText: {
        marginTop: 8,
        fontSize: 14,
        lineHeight: 22,
        color: Colors.textSecondary,
        textAlign: 'center',
    },
});
