import { StyleSheet } from 'react-native';
import Colors from '@styles/colors';
import { editorialShadow } from '@styles/theme';

export default StyleSheet.create({
    container: { flex: 1, backgroundColor: Colors.surface },
    headerCard: {
        backgroundColor: Colors.surfaceContainerLowest,
        borderRadius: 24,
        padding: 20,
        marginBottom: 12,
        ...editorialShadow,
    },
    headerTitle: { fontSize: 24, fontWeight: '800', color: Colors.text },
    headerSubtitle: { fontSize: 14, color: Colors.textSecondary, marginTop: 8, lineHeight: 21 },
    card: {
        backgroundColor: Colors.surfaceContainerLowest,
        borderRadius: 24,
        marginBottom: 12,
        ...editorialShadow,
    },
    cardContent: { flexDirection: 'row', padding: 14 },
    image: { width: 100, height: 100, borderRadius: 18 },
    imagePlaceholder: { backgroundColor: Colors.surfaceContainerLow, justifyContent: 'center', alignItems: 'center' },
    cardBody: { flex: 1, marginLeft: 14 },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
    name: { fontSize: 16, fontWeight: '800', color: Colors.text, lineHeight: 21, flex: 1, marginRight: 8 },
    meta: { fontSize: 12, color: Colors.textSecondary, marginTop: 4 },
    price: { fontSize: 16, color: Colors.primary, fontWeight: '800', marginTop: 6 },
    cardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10 },
    stepper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.surfaceContainerLow,
        borderRadius: 14,
        paddingHorizontal: 4,
        paddingVertical: 4,
    },
    stepIconBtn: { width: 32, height: 32, borderRadius: 10, backgroundColor: Colors.surfaceContainerLowest, margin: 0 },
    quantity: { minWidth: 30, textAlign: 'center', fontSize: 16, fontWeight: '800', color: Colors.text },
    lineTotal: { fontSize: 15, fontWeight: '800', color: Colors.text },
    bottomSheet: {
        position: 'absolute',
        left: 0,
        right: 0,
        backgroundColor: Colors.surface + 'CC',
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        paddingHorizontal: 20,
        paddingTop: 18,
        paddingBottom: 30,
        ...editorialShadow,
    },
    sheetTitle: { fontSize: 16, fontWeight: '800', color: Colors.text },
    paymentRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 12 },
    chip: {
        marginRight: 8,
        marginBottom: 8,
    },
    chipText: { fontSize: 13, fontWeight: '700' },
    summaryBlock: {
        backgroundColor: Colors.surfaceContainerHigh,
        borderRadius: 16,
        padding: 14,
        marginTop: 8,
    },
    summaryRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    summaryLabel: { fontSize: 15, color: Colors.textSecondary, fontWeight: '700' },
    summaryAmount: { fontSize: 24, fontWeight: '800', color: Colors.primary },
    empty: {
        flex: 1,
        backgroundColor: Colors.surface,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 32,
    },
    emptyIconCircle: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: Colors.primaryLight,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 18,
    },
    emptyTitle: { fontSize: 24, fontWeight: '800', color: Colors.text },
    emptyText: { fontSize: 15, color: Colors.textSecondary, textAlign: 'center', marginTop: 10, lineHeight: 22 },
    guestPrompt: { paddingTop: 4 },
    guestPromptIcon: {
        width: 56,
        height: 56,
        borderRadius: 18,
        backgroundColor: Colors.primaryLight,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'flex-start',
        marginBottom: 12,
    },
    guestPromptTitle: {
        fontSize: 17,
        fontWeight: '800',
        color: Colors.text,
    },
    guestPromptText: {
        fontSize: 13,
        color: Colors.textSecondary,
        marginTop: 6,
        lineHeight: 19,
    },
});
