import { StyleSheet } from 'react-native';
import Colors from '@styles/colors';

const styles = StyleSheet.create({
    container: { padding: 28, paddingTop: 20 },
    bgBlob: {
        position: 'absolute',
        top: -50,
        right: -70,
        width: 200,
        height: 200,
        borderRadius: 100,
        backgroundColor: Colors.primaryLight,
        opacity: 0.5,
    },
    pageTitle: { fontSize: 32, fontWeight: '800', color: Colors.text, marginBottom: 28 },
    avatarWrap: { alignSelf: 'center', marginBottom: 8 },
    avatar: { width: 112, height: 112, borderRadius: 56, borderWidth: 3, borderColor: Colors.outlineVariant + '40' },
    avatarPlaceholder: {
        width: 112,
        height: 112,
        borderRadius: 56,
        backgroundColor: Colors.surfaceContainerLow,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: Colors.outline,
        borderStyle: 'dashed',
    },
    cameraBadge: {
        position: 'absolute',
        right: -4,
        bottom: -4,
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: Colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 3,
        borderColor: Colors.surface,
    },
    avatarLabel: { textAlign: 'center', fontSize: 11, color: Colors.textSecondary, fontWeight: '700', marginTop: 8, marginBottom: 24, letterSpacing: 1 },
    notice: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.primaryLight,
        padding: 16,
        borderRadius: 16,
        marginBottom: 24,
    },
    noticeText: { flex: 1, fontSize: 13, color: Colors.primary, marginLeft: 10, lineHeight: 19 },
    label: { fontSize: 11, color: Colors.textSecondary, fontWeight: '700', marginBottom: 8, letterSpacing: 1 },
    nameRow: { flexDirection: 'row' },
    addressBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.surfaceContainerLowest,
        borderRadius: 16,
        padding: 14,
        marginBottom: 16,
        borderWidth: 1.5,
        borderColor: Colors.outline,
    },
    addressText: { flex: 1, marginLeft: 12, fontSize: 15, color: Colors.text, fontWeight: '600', lineHeight: 21 },
    addressPlaceholder: { color: Colors.placeholder, fontWeight: '400' },
    footer: { flexDirection: 'row', justifyContent: 'center', marginTop: 28, marginBottom: 12 },
    footerText: { color: Colors.textSecondary, fontSize: 14 },
    footerLink: { color: Colors.primary, fontSize: 14, fontWeight: '800' },
    chefLink: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginBottom: 40 },
    chefLinkText: { color: Colors.primary, fontSize: 14, fontWeight: '700', marginLeft: 8 },
});

export default styles;
