# Generated by Django 6.0.3 on 2026-03-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tablebooking',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/'),
        ),
    ]
