# Generated by Django 4.2.28 on 2026-05-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
