# Generated by Django 4.2.28 on 2026-05-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('provider', models.CharField(choices=[('momo', 'MoMo'), ('stripe', 'Stripe')], max_length=10)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField()),
                ('signature_valid', models.BooleanField(default=False)),
                ('result', models.CharField(choices=[('updated', 'Da cap nhat payment'), ('duplicate', 'Trung event (bo qua)'), ('unknown_payment', 'Khong tim thay payment'), ('invalid_signature', 'Sai chu ky'), ('invalid_payload', 'Payload loi')], max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='restaurant.payment')),
            ],
            options={
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['provider', 'created_date'], name='restaurant__provide_1fa10f_idx')],
            },
        ),
    ]
