# Generated by Codex on 2026-05-14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def backfill_payment_finance_fields(apps, schema_editor):
    Payment = apps.get_model('restaurant', 'Payment')
    PaymentAttempt = apps.get_model('restaurant', 'PaymentAttempt')
    for payment in Payment.objects.all().iterator():
        update_fields = []
        if payment.status == 'completed' and payment.paid_at is None:
            payment.paid_at = payment.created_date
            update_fields.append('paid_at')
        if not payment.gateway_request_id and payment.transaction_id:
            payment.gateway_request_id = payment.transaction_id
            update_fields.append('gateway_request_id')
        if payment.status == 'failed' and not payment.failure_reason:
            payment.failure_reason = 'Trang thai that bai truoc khi them attempt log.'
            update_fields.append('failure_reason')
        if update_fields:
            payment.save(update_fields=update_fields)
        if payment.method in ('momo', 'stripe') and payment.current_attempt_id is None:
            attempt = PaymentAttempt.objects.create(
                payment=payment,
                method=payment.method,
                status=payment.status,
                amount=payment.amount,
                gateway_request_id=payment.gateway_request_id,
                gateway_order_id=payment.gateway_order_id,
                transaction_id=payment.transaction_id,
                pay_url=payment.pay_url,
                deeplink_url=payment.deeplink_url,
                qr_code_url=payment.qr_code_url,
                expires_at=payment.expires_at,
                paid_at=payment.paid_at,
                failure_reason=payment.failure_reason,
            )
            payment.current_attempt = attempt
            payment.save(update_fields=['current_attempt'])


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_webhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deeplink_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='qr_code_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Tiền mặt khi nhận'), ('momo', 'MoMo'), ('stripe', 'Stripe')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('gateway_request_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('gateway_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_url', models.URLField(blank=True, max_length=500, null=True)),
                ('deeplink_url', models.URLField(blank=True, max_length=500, null=True)),
                ('qr_code_url', models.URLField(blank=True, max_length=500, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='restaurant.payment')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [
                    models.Index(fields=['method', 'status'], name='restaurant__method_26d688_idx'),
                ],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='current_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='restaurant.paymentattempt'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='restaurant.paymentattempt'),
        ),
        migrations.RunPython(backfill_payment_finance_fields, migrations.RunPython.noop),
    ]
