# Generated by Django 4.2.28 on 2026-05-23 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_payment_attempt_finance_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentattempt',
            new_name='restaurant__method_40c27a_idx',
            old_name='restaurant__method_26d688_idx',
        ),
    ]
