import { StyleSheet } from 'react-native';
import Colors from '@styles/colors';
import { editorialShadow } from '@styles/theme';

export default StyleSheet.create({
    heroWrap: { position: 'relative' },
    img: { width: '100%', height: 300, borderBottomLeftRadius: 28, borderBottomRightRadius: 28 },
    imagePlaceholder: { backgroundColor: Colors.surfaceContainerLow, justifyContent: 'center', alignItems: 'center' },
    ratingOverlay: {
        position: 'absolute',
        bottom: 16,
        right: 16,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.surfaceContainerLowest + 'E6',
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 16,
        ...editorialShadow,
    },
    ratingOverlayText: { color: Colors.text, fontWeight: '800', marginLeft: 6, fontSize: 16 },
    ratingOverlaySub: { color: Colors.textSecondary, fontSize: 13 },
    infoBox: { paddingBottom: 8 },
    titleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        paddingHorizontal: 20,
        paddingTop: 24,
    },
    name: { fontSize: 28, fontWeight: '800', color: Colors.text, flex: 1, marginRight: 12, lineHeight: 34 },
    price: { fontSize: 24, color: Colors.primary, fontWeight: '800' },
    desc: { fontSize: 15, color: Colors.textSecondary, paddingHorizontal: 20, marginTop: 12, lineHeight: 24 },
    tagRow: { flexDirection: 'row', flexWrap: 'wrap', paddingHorizontal: 20, marginTop: 16 },
    tagChip: { marginRight: 8, marginBottom: 8, backgroundColor: Colors.primaryLight },
    tagChipText: { color: Colors.text, fontSize: 13, fontWeight: '600' },
    sectionCard: {
        marginHorizontal: 20,
        marginTop: 18,
        padding: 20,
        backgroundColor: Colors.surfaceContainerLowest,
        borderRadius: 24,
        ...editorialShadow,
    },
    sectionTitle: { fontSize: 20, fontWeight: '800', color: Colors.text, marginBottom: 12 },
    ingredients: { fontSize: 15, color: Colors.textSecondary, lineHeight: 22 },
    ingredientGrid: { flexDirection: 'row', flexWrap: 'wrap' },
    ingredientChip: { marginRight: 8, marginBottom: 8 },
    ingredientText: { fontSize: 13, color: Colors.text, fontWeight: '600' },
    starRow: { flexDirection: 'row', marginBottom: 14 },
    starBtn: { marginRight: 4 },
    reviewHeader: { marginHorizontal: 20, marginTop: 10 },
    reviewItem: {
        padding: 16,
        marginHorizontal: 20,
        marginVertical: 5,
        backgroundColor: Colors.surfaceContainerLowest,
        borderRadius: 20,
        ...editorialShadow,
    },
    reviewTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    reviewAuthor: { fontSize: 15, fontWeight: '700', color: Colors.text },
    reviewDate: { fontSize: 12, color: Colors.textSecondary, marginTop: 4 },
    reviewStarBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.star + '15',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 10,
    },
    reviewStarText: { color: Colors.star, fontWeight: '700', fontSize: 14, marginLeft: 4 },
    reviewComment: { color: Colors.text, fontSize: 15, lineHeight: 22, marginTop: 10 },
    emptyReview: { alignItems: 'center', marginTop: 16, paddingHorizontal: 24 },
    emptyReviewText: { fontSize: 14, color: Colors.textSecondary, marginTop: 10, textAlign: 'center' },
    bottomBar: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.surface + 'CC',
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        paddingHorizontal: 18,
        paddingVertical: 14,
        paddingBottom: 28,
        ...editorialShadow,
    },
    stepper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.surfaceContainerLow,
        borderRadius: 20,
        paddingHorizontal: 2,
        paddingVertical: 2,
    },
    stepBtn: { width: 38, height: 38, borderRadius: 14, backgroundColor: Colors.surfaceContainerLowest },
    quantityText: { minWidth: 36, textAlign: 'center', fontSize: 18, fontWeight: '800', color: Colors.text },
    cartBtn: {
        borderRadius: 20,
        flex: 1,
        marginLeft: 12,
    },
    centerState: {
        flex: 1,
        backgroundColor: Colors.surface,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 32,
    },
    stateTitle: { fontSize: 22, fontWeight: '800', color: Colors.text, marginTop: 16 },
    stateText: { fontSize: 15, color: Colors.textSecondary, textAlign: 'center', marginTop: 10, lineHeight: 22 },
});
