import { StyleSheet } from 'react-native';
import Colors from '@styles/colors';
import { editorialShadow } from '@styles/theme';

export default StyleSheet.create({
    container: { flex: 1, backgroundColor: Colors.surface },
    banner: {
        backgroundColor: Colors.primary,
        paddingVertical: 28,
        paddingHorizontal: 20,
        overflow: 'hidden',
    },
    bannerBlob1: {
        position: 'absolute',
        top: -30,
        right: -20,
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: '#ffffff10',
    },
    bannerBlob2: {
        position: 'absolute',
        bottom: -40,
        left: -30,
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#ffffff08',
    },
    bannerContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    bannerLogo: {
        width: 48,
        height: 48,
        borderRadius: 16,
        backgroundColor: '#ffffff20',
        justifyContent: 'center',
        alignItems: 'center',
        transform: [{ rotate: '-3deg' }],
    },
    bannerLogoText: { fontSize: 26, fontWeight: '900', fontStyle: 'italic', color: Colors.onPrimary },
    bannerName: { color: Colors.onPrimary, fontSize: 18, fontWeight: '900', letterSpacing: 2 },
    bannerSub: { color: Colors.onPrimary + 'B3', fontSize: 13, fontWeight: '600', marginTop: 4 },
    bannerTagRow: { flexDirection: 'row', marginTop: 16, gap: 8 },
    bannerTag: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ffffff18',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 10,
    },
    bannerTagText: { color: Colors.onPrimary, fontSize: 12, fontWeight: '700', marginLeft: 5 },
    searchRow: { flexDirection: 'row', paddingHorizontal: 16, paddingTop: 8, alignItems: 'center' },
    searchbar: {
        flex: 1,
        borderRadius: 20,
        backgroundColor: Colors.surfaceContainerLowest,
        marginRight: 10,
        ...editorialShadow,
    },
    filterBtn: { borderRadius: 20 },
    compareFab: {
        position: 'absolute',
        right: 16,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.text,
        paddingHorizontal: 18,
        paddingVertical: 14,
        borderRadius: 20,
        ...editorialShadow,
    },
    compareFabText: { color: Colors.onPrimary, fontSize: 14, fontWeight: '800', marginLeft: 8 },
    errorCard: {
        marginHorizontal: 16,
        marginTop: 6,
        marginBottom: 10,
        backgroundColor: Colors.surfaceContainerLowest,
        borderRadius: 20,
        padding: 16,
        flexDirection: 'row',
        alignItems: 'center',
        ...editorialShadow,
    },
    errorTitle: { fontSize: 15, fontWeight: '700', color: Colors.text },
    errorText: { fontSize: 13, color: Colors.textSecondary, marginTop: 4, lineHeight: 18 },
    empty: { alignItems: 'center', marginTop: 36, paddingHorizontal: 32, paddingBottom: 10 },
    emptyTitle: { fontSize: 18, fontWeight: '800', color: Colors.text, marginTop: 14 },
    emptyText: { fontSize: 14, color: Colors.textSecondary, marginTop: 8, textAlign: 'center', lineHeight: 21 },
});
