import { StyleSheet } from 'react-native';
import Colors from '@styles/colors';
import { editorialShadow } from '@styles/theme';

export default StyleSheet.create({
    container: { flex: 1, backgroundColor: Colors.surface },
    header: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 10 },
    headerRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 12 },
    headerTitle: { fontSize: 26, fontWeight: '800', color: Colors.text, letterSpacing: -0.3 },
    headerSubtitle: { fontSize: 14, color: Colors.textSecondary, marginTop: 6, lineHeight: 20 },
    refreshBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: Colors.surfaceContainerLow,
        justifyContent: 'center',
        alignItems: 'center',
    },
    filterScroll: {
        gap: 8,
        paddingTop: 14,
        paddingRight: 4,
    },
    filterChip: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 9999,
        backgroundColor: Colors.surfaceContainerLow,
        borderWidth: 1,
        borderColor: 'transparent',
    },
    filterChipActive: {
        backgroundColor: Colors.primaryLight,
        borderColor: Colors.primary,
    },
    filterChipText: {
        fontSize: 13,
        fontWeight: '700',
        color: Colors.textSecondary,
    },
    filterChipTextActive: {
        color: Colors.primary,
    },
    errorCard: {
        marginHorizontal: 16,
        marginTop: 16,
        marginBottom: 4,
        backgroundColor: Colors.surfaceContainerLowest,
        borderRadius: 20,
        padding: 14,
        flexDirection: 'row',
        alignItems: 'center',
        ...editorialShadow,
    },
    errorText: { flex: 1, marginLeft: 10, color: Colors.text, fontSize: 14, lineHeight: 20 },

    // Card Styles
    card: {
        backgroundColor: Colors.surfaceContainerLowest,
        marginHorizontal: 16,
        marginVertical: 8,
        borderRadius: 24,
        padding: 18,
        ...editorialShadow,
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 4,
    },
    cardCancelled: { opacity: 0.65 },
    cardHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
    orderId: { fontSize: 17, fontWeight: '800', color: Colors.text, letterSpacing: -0.2 },
    date: { fontSize: 12, color: Colors.textSecondary, marginTop: 4, fontWeight: '500' },
    badge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 9999,
        marginLeft: 12,
    },
    badgeText: { fontSize: 11, fontWeight: '800', letterSpacing: 0.2 },

    serviceRow: {
        marginTop: 16,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    serviceIcon: {
        width: 40,
        height: 40,
        borderRadius: 12,
        backgroundColor: Colors.primaryLight,
        alignItems: 'center',
        justifyContent: 'center',
    },
    serviceTitle: {
        color: Colors.text,
        fontSize: 14,
        fontWeight: '800',
    },
    serviceSub: {
        color: Colors.textSecondary,
        fontSize: 12,
        lineHeight: 18,
        marginTop: 2,
        fontWeight: '500',
    },

    paymentBlock: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        marginTop: 16,
        padding: 14,
        backgroundColor: Colors.surfaceContainerLow,
        borderRadius: 16,
    },
    paymentInfoCol: { flex: 1 },
    amountCol: { alignItems: 'flex-end', marginLeft: 12 },
    summaryLabel: {
        fontSize: 11,
        fontWeight: '700',
        color: Colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 0.8,
        marginBottom: 6,
    },
    amount: { fontSize: 20, fontWeight: '800', color: Colors.primary, letterSpacing: -0.5 },
    paymentMethodRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    paymentMethodText: { fontSize: 13, fontWeight: '700', color: Colors.text },
    payPill: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
        marginLeft: 4,
    },
    payPillText: {
        fontSize: 10,
        fontWeight: '800',
        letterSpacing: 0.2,
        textTransform: 'uppercase',
    },

    divider: {
        height: 1,
        backgroundColor: Colors.outlineVariant + '40',
        marginTop: 16,
        marginBottom: 16,
    },

    actionsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    detailsToggleLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    detailsToggleText: { fontSize: 14, fontWeight: '700', color: Colors.text },
    viewDetailBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: Colors.primaryLight,
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 12,
    },
    viewDetailText: {
        color: Colors.primary,
        fontSize: 13,
        fontWeight: '800',
    },

    empty: { alignItems: 'center', marginTop: 60, paddingHorizontal: 32 },
    emptyIconCircle: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: Colors.surfaceContainerLow,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
    },
    emptyTitle: { fontSize: 22, fontWeight: '800', color: Colors.text, textAlign: 'center' },
    emptyText: { fontSize: 14, color: Colors.textSecondary, marginTop: 12, lineHeight: 22, textAlign: 'center' },
});
