import { StyleSheet } from 'react-native';
import Colors from '@styles/colors';
import { editorialShadow } from '@styles/theme';

export default StyleSheet.create({
    container: { flex: 1, backgroundColor: Colors.surface },
    header: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 10 },
    headerTitle: { fontSize: 26, fontWeight: '800', color: Colors.text },
    headerSubtitle: { fontSize: 14, color: Colors.textSecondary, marginTop: 8, lineHeight: 21 },
    errorCard: {
        marginHorizontal: 16,
        marginTop: 16,
        marginBottom: 4,
        backgroundColor: Colors.surfaceContainerLowest,
        borderRadius: 20,
        padding: 14,
        flexDirection: 'row',
        alignItems: 'center',
        ...editorialShadow,
    },
    errorText: { flex: 1, marginLeft: 10, color: Colors.text, fontSize: 14, lineHeight: 20 },
    card: {
        backgroundColor: Colors.surfaceContainerLowest,
        marginHorizontal: 16,
        marginVertical: 6,
        borderRadius: 24,
        padding: 18,
        ...editorialShadow,
    },
    cardHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
    orderId: { fontSize: 18, fontWeight: '800', color: Colors.text },
    badge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 9999,
        marginLeft: 12,
    },
    badgeDot: { width: 6, height: 6, borderRadius: 3, marginRight: 6 },
    badgeText: { fontSize: 12, fontWeight: '700' },
    amount: { fontSize: 24, fontWeight: '800', color: Colors.primary, marginTop: 12 },
    date: { fontSize: 13, color: Colors.textSecondary, marginTop: 6 },
    paymentBlock: {
        marginTop: 16,
        backgroundColor: Colors.surfaceContainerLow,
        borderRadius: 18,
        padding: 14,
        flexDirection: 'row',
        alignItems: 'center',
    },
    paymentIconWrap: {
        width: 36,
        height: 36,
        borderRadius: 12,
        backgroundColor: Colors.tertiaryLight,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    paymentText: { fontSize: 15, fontWeight: '700', color: Colors.text },
    paymentStatus: { fontSize: 13, color: Colors.textSecondary, marginTop: 4 },
    detailList: { marginTop: 16 },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
    },
    detailQtyBadge: {
        backgroundColor: Colors.primaryLight,
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 8,
        marginRight: 10,
    },
    detailQtyText: { fontSize: 12, fontWeight: '700', color: Colors.primary },
    detailItem: { flex: 1, paddingRight: 12, fontSize: 14, color: Colors.text, fontWeight: '600' },
    detailPrice: { fontSize: 13, color: Colors.textSecondary, fontWeight: '700' },
    empty: { alignItems: 'center', marginTop: 40, paddingHorizontal: 32 },
    emptyIconCircle: {
        width: 72,
        height: 72,
        borderRadius: 36,
        backgroundColor: Colors.primaryLight,
        justifyContent: 'center',
        alignItems: 'center',
    },
    emptyTitle: { fontSize: 22, fontWeight: '800', color: Colors.text, marginTop: 18 },
    emptyText: { fontSize: 14, color: Colors.textSecondary, marginTop: 10, lineHeight: 22, textAlign: 'center' },
});
