$kind: http-request
url: "{{base_url}}/swagger.json"
method: GET
auth:
  type: noauth
scripts:
  - type: afterResponse
    code: |-
      pm.test('Status 200', () => pm.response.to.have.status(200));
      pm.test('Có info.title', () => pm.expect(pm.response.json().info.title).to.include('T-Restaurant'));
    language: text/javascript
order: 2000
