import { StyleSheet } from 'react-native';
import Colors from '@styles/colors';
import { editorialShadow } from '@styles/theme';

export default StyleSheet.create({
    segmentedRow: { paddingHorizontal: 16, paddingTop: 12 },
    form: { padding: 20 },
    summaryCard: {
        backgroundColor: Colors.surfaceContainerLowest,
        borderRadius: 24,
        padding: 20,
        marginBottom: 20,
        ...editorialShadow,
    },
    summaryIcon: {
        width: 48,
        height: 48,
        borderRadius: 16,
        backgroundColor: Colors.primaryLight,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
    },
    summaryTitle: { fontSize: 12, color: Colors.textSecondary, fontWeight: '700', letterSpacing: 1 },
    summaryValue: { fontSize: 24, fontWeight: '800', color: Colors.text, marginTop: 8 },
    summaryHint: { fontSize: 14, color: Colors.textSecondary, marginTop: 8, lineHeight: 21 },
    label: { fontSize: 11, color: Colors.textSecondary, fontWeight: '700', marginBottom: 8, letterSpacing: 1 },
    pickerBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.surfaceContainerLowest,
        borderRadius: 20,
        padding: 16,
        marginBottom: 18,
        borderWidth: 1.5,
        borderColor: Colors.outline,
    },
    pickerText: { fontSize: 17, color: Colors.text, fontWeight: '700', marginLeft: 12 },
    suggestedLabel: { fontSize: 11, color: Colors.textSecondary, fontWeight: '700', marginBottom: 8, letterSpacing: 1 },
    suggestedRow: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 18 },
    suggestedChip: {
        marginRight: 8,
        marginBottom: 8,
    },
    suggestedChipActive: { borderColor: Colors.primary, backgroundColor: Colors.primaryLight },
    suggestedText: { fontSize: 13, fontWeight: '600', color: Colors.textSecondary },
    suggestedTextActive: { color: Colors.primary, fontWeight: '700' },
    guestStepper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.surfaceContainerLowest,
        borderRadius: 20,
        paddingHorizontal: 6,
        paddingVertical: 6,
        marginBottom: 18,
        alignSelf: 'flex-start',
        borderWidth: 1.5,
        borderColor: Colors.outline,
    },
    guestStepIconBtn: {
        width: 42,
        height: 42,
        borderRadius: 14,
        backgroundColor: Colors.surfaceContainerLow,
        margin: 0,
    },
    guestCount: { minWidth: 50, textAlign: 'center', fontSize: 20, fontWeight: '800', color: Colors.text },
    historyHeader: { paddingHorizontal: 18, paddingBottom: 8 },
    historyTitle: { fontSize: 26, fontWeight: '800', color: Colors.text },
    historySubtitle: { fontSize: 14, color: Colors.textSecondary, marginTop: 8, lineHeight: 21 },
    bookingCard: {
        backgroundColor: Colors.surfaceContainerLowest,
        marginHorizontal: 16,
        marginVertical: 6,
        borderRadius: 24,
        padding: 18,
        ...editorialShadow,
    },
    bookingHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
    bookingDate: { fontSize: 16, fontWeight: '800', color: Colors.text, lineHeight: 22 },
    bookingInfoRow: { flexDirection: 'row', marginTop: 8 },
    bookingInfoChip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.surfaceContainerLow,
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 9999,
    },
    bookingInfoText: { fontSize: 13, color: Colors.text, fontWeight: '600', marginLeft: 4 },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 9999,
        marginLeft: 10,
    },
    statusDot: { width: 6, height: 6, borderRadius: 3, marginRight: 6 },
    statusText: { fontSize: 12, fontWeight: '700' },
    noteBlock: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: Colors.surfaceContainerLow,
        padding: 12,
        borderRadius: 14,
        marginTop: 12,
    },
    bookingNote: { fontSize: 14, color: Colors.text, marginLeft: 8, flex: 1, lineHeight: 20, fontStyle: 'italic' },
    empty: { alignItems: 'center', marginTop: 40, paddingHorizontal: 32 },
    emptyIconWrap: {
        width: 72,
        height: 72,
        borderRadius: 36,
        backgroundColor: Colors.primaryLight,
        justifyContent: 'center',
        alignItems: 'center',
    },
    emptyTitle: { fontSize: 22, fontWeight: '800', color: Colors.text, marginTop: 18 },
    emptyText: { fontSize: 14, color: Colors.textSecondary, marginTop: 10, lineHeight: 22, textAlign: 'center' },
});
