import { StyleSheet } from 'react-native';
import Colors from '@styles/colors';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.surface,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 12,
        paddingVertical: 10,
        backgroundColor: Colors.surfaceContainerLowest,
        borderBottomWidth: 1,
        borderBottomColor: Colors.outlineVariant + '40',
    },
    headerBtn: {
        minWidth: 56,
        paddingHorizontal: 8,
        paddingVertical: 6,
        alignItems: 'center',
    },
    headerTitle: {
        flex: 1,
        textAlign: 'center',
        fontSize: 16,
        fontWeight: '800',
        color: Colors.text,
        letterSpacing: -0.2,
    },
    cancelText: {
        fontSize: 14,
        fontWeight: '700',
        color: Colors.primary,
    },
    countdownBar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 8,
        backgroundColor: Colors.primaryLight,
        borderBottomWidth: 1,
        borderBottomColor: Colors.outlineVariant + '30',
    },
    countdownText: {
        fontSize: 13,
        fontWeight: '800',
        color: Colors.primary,
    },
    loadingOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Colors.surface,
    },
    confirmingOverlay: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: Colors.surface + 'F0',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 32,
    },
    confirmingText: {
        marginTop: 18,
        fontSize: 17,
        fontWeight: '800',
        color: Colors.text,
    },
    confirmingSub: {
        marginTop: 6,
        fontSize: 13,
        color: Colors.textSecondary,
    },
    gatewayHelpPanel: {
        position: 'absolute',
        left: 18,
        right: 18,
        bottom: 26,
        backgroundColor: Colors.surfaceContainerLowest,
        borderRadius: 18,
        padding: 18,
        borderWidth: 1,
        borderColor: Colors.outlineVariant + '50',
        alignItems: 'center',
    },
    gatewayHelpClose: {
        position: 'absolute',
        top: 10,
        right: 10,
        width: 32,
        height: 32,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    gatewayHelpTitle: {
        marginTop: 10,
        fontSize: 16,
        fontWeight: '800',
        color: Colors.text,
        textAlign: 'center',
    },
    gatewayHelpText: {
        marginTop: 6,
        fontSize: 13,
        lineHeight: 19,
        color: Colors.textSecondary,
        textAlign: 'center',
    },
    qrImage: {
        width: 152,
        height: 152,
        marginTop: 14,
        borderRadius: 8,
    },
    gatewayHelpActions: {
        flexDirection: 'row',
        gap: 10,
        marginTop: 16,
    },
    primaryAction: {
        minHeight: 42,
        paddingHorizontal: 18,
        borderRadius: 12,
        backgroundColor: Colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
    },
    primaryActionText: {
        color: Colors.onPrimary,
        fontSize: 14,
        fontWeight: '800',
    },
    secondaryAction: {
        minHeight: 42,
        paddingHorizontal: 18,
        borderRadius: 12,
        backgroundColor: Colors.surfaceContainerLow,
        alignItems: 'center',
        justifyContent: 'center',
    },
    secondaryActionText: {
        color: Colors.primary,
        fontSize: 14,
        fontWeight: '800',
    },
});
