import { StyleSheet, Platform } from 'react-native';
import Colors from '@styles/colors';

const cardShadow = Platform.select({
    ios: {
        shadowColor: '#271816',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.06,
        shadowRadius: 14,
    },
    android: { elevation: 2 },
    default: {},
});

export default StyleSheet.create({
    container: { flex: 1, backgroundColor: Colors.surface },
    header: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 12,
        paddingHorizontal: 18,
        paddingTop: 12,
        paddingBottom: 14,
    },
    headerBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: Colors.surfaceContainerLow,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 2,
    },
    title: {
        fontSize: 25,
        fontWeight: '900',
        color: Colors.text,
        letterSpacing: -0.3,
    },
    subtitle: {
        color: Colors.textSecondary,
        fontSize: 13,
        lineHeight: 19,
        marginTop: 5,
        fontWeight: '600',
    },
    content: {
        paddingHorizontal: 16,
        paddingTop: 4,
    },
    summaryCard: {
        borderRadius: 22,
        backgroundColor: Colors.surfaceContainerLowest,
        padding: 18,
        borderWidth: 1,
        borderColor: Colors.outlineVariant + '40',
        ...cardShadow,
    },
    summaryTop: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        gap: 12,
    },
    summaryLabel: {
        color: Colors.textSecondary,
        fontSize: 11,
        fontWeight: '800',
        textTransform: 'uppercase',
        letterSpacing: 0.8,
    },
    amount: {
        color: Colors.primary,
        fontSize: 28,
        fontWeight: '900',
        marginTop: 6,
        letterSpacing: -0.4,
    },
    orderBadge: {
        borderRadius: 9999,
        backgroundColor: Colors.primaryLight,
        paddingHorizontal: 12,
        paddingVertical: 7,
    },
    orderBadgeText: {
        color: Colors.primary,
        fontSize: 13,
        fontWeight: '900',
    },
    serviceRow: {
        marginTop: 16,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    serviceIcon: {
        width: 38,
        height: 38,
        borderRadius: 14,
        backgroundColor: Colors.primaryLight,
        alignItems: 'center',
        justifyContent: 'center',
    },
    serviceTitle: {
        color: Colors.text,
        fontSize: 14,
        fontWeight: '900',
    },
    serviceSub: {
        color: Colors.textSecondary,
        fontSize: 12,
        lineHeight: 17,
        marginTop: 3,
        fontWeight: '600',
    },
    sectionTitle: {
        marginTop: 22,
        marginBottom: 10,
        color: Colors.text,
        fontSize: 14,
        fontWeight: '900',
        textTransform: 'uppercase',
        letterSpacing: 0.7,
    },
    paymentOption: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        borderRadius: 18,
        borderWidth: 2,
        borderColor: Colors.outlineVariant + '45',
        backgroundColor: Colors.surfaceContainerLowest,
        padding: 14,
        marginBottom: 10,
    },
    paymentOptionActive: {
        borderColor: Colors.primary,
        backgroundColor: Colors.primaryLight,
    },
    paymentIcon: {
        width: 46,
        height: 46,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.surfaceContainerLow,
    },
    paymentIconActive: {
        backgroundColor: Colors.surfaceContainerLowest,
    },
    paymentTitle: {
        color: Colors.text,
        fontSize: 15,
        fontWeight: '900',
    },
    paymentTitleActive: {
        color: Colors.primary,
    },
    paymentDesc: {
        color: Colors.textSecondary,
        fontSize: 12,
        lineHeight: 17,
        marginTop: 3,
        fontWeight: '600',
    },
    bottomBar: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: Colors.surfaceContainerLowest,
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        paddingHorizontal: 18,
        paddingTop: 14,
        borderTopWidth: 1,
        borderTopColor: Colors.outlineVariant + '30',
        ...cardShadow,
    },
    paySummary: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    paySummaryLabel: {
        color: Colors.textSecondary,
        fontSize: 12,
        fontWeight: '800',
    },
    paySummaryValue: {
        color: Colors.text,
        fontSize: 13,
        fontWeight: '900',
    },
    payBtn: {
        height: 54,
        borderRadius: 18,
        backgroundColor: Colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        gap: 8,
    },
    payBtnDisabled: {
        opacity: 0.75,
    },
    payBtnText: {
        color: Colors.onPrimary,
        fontSize: 16,
        fontWeight: '900',
    },
    centerState: {
        flex: 1,
        backgroundColor: Colors.surface,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 28,
    },
    stateTitle: {
        color: Colors.text,
        fontSize: 22,
        fontWeight: '900',
        marginTop: 14,
    },
    stateText: {
        color: Colors.textSecondary,
        fontSize: 14,
        textAlign: 'center',
        marginTop: 8,
        lineHeight: 21,
    },
    stateBtn: {
        marginTop: 20,
        borderRadius: 18,
    },
});
